version: '3'
services:
  webapp:
    image: calculator-wui:{{service.CALCULATOR_WUI.hash}}
    depends_on:
      - "database"
    command: ["./wait-for-postgres.sh", "database", "catalina.sh", "run"]
    restart: always
  database:
    image: calculator-database:{{service.CALCULATOR_DATABASE.hash}}
    restart: always
  geoserver:
    image: calculator-geoserver:{{service.SCENARIO_BASE_GEOSERVER.hash}}
    depends_on:
      - "database"
    command: ["./wait-for-postgres.sh", "database", "catalina.sh", "run"]
    restart: always
